# Netlify configuration for the frontend app (inside /frontend)

[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # You can set this in Netlify UI instead of committing a value
  # VITE_API_BASE_URL = "https://api.example.com"

## Local development via `netlify dev`
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

## SPA fallback: route all non-file paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API to backend in production (Netlify)
[[redirects]]
  from = "/auth/*"
  to = "http://75.119.145.146:8899/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ai/*"
  to = "http://75.119.145.146:8899/ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/student/*"
  to = "http://75.119.145.146:8899/student/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "http://75.119.145.146:8899/api/:splat"
  status = 200
  force = true

## Long-term cache for hashed assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

## Example per-environment overrides
[context.production.environment]
  # VITE_API_BASE_URL = "https://api.prod.example.com"

[context.deploy-preview.environment]
  # VITE_API_BASE_URL = "https://api-preview.example.com"

